-- Production telemetry schema for anonymous run uploads.
-- Run in Supabase SQL editor after the connectivity spike is validated.

create table if not exists public.telemetry_runs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  run_id text not null,
  started_at_unix bigint not null,
  ended_at_unix bigint not null,
  game_version text not null,
  difficulty_tier int not null,
  run_mode int not null,
  outcome text not null,
  max_depth int not null,
  rooms_cleared int not null,
  is_debug boolean not null,
  death_event jsonb not null default '{}'::jsonb,
  damage_events jsonb not null default '[]'::jsonb,
  reward_choices jsonb not null default '[]'::jsonb,
  room_entries jsonb not null default '[]'::jsonb,
  door_choices jsonb not null default '[]'::jsonb,
  aggregate jsonb not null default '{}'::jsonb,
  upload_source text not null default 'game_client'
);

alter table public.telemetry_runs add column if not exists damage_events jsonb not null default '[]'::jsonb;
alter table public.telemetry_runs add column if not exists reward_choices jsonb not null default '[]'::jsonb;
alter table public.telemetry_runs add column if not exists room_entries jsonb not null default '[]'::jsonb;
alter table public.telemetry_runs add column if not exists door_choices jsonb not null default '[]'::jsonb;

create unique index if not exists telemetry_runs_run_id_idx
  on public.telemetry_runs (run_id);

alter table public.telemetry_runs enable row level security;

-- Restrict anonymous writes to expected shape and bounded values.
drop policy if exists telemetry_runs_insert_anon on public.telemetry_runs;
create policy telemetry_runs_insert_anon
on public.telemetry_runs
for insert
to anon
with check (
  length(trim(run_id)) >= 8
  and started_at_unix > 0
  and ended_at_unix >= started_at_unix
  and difficulty_tier between 0 and 3
  and run_mode in (0, 1)
  and outcome in ('clear', 'death', 'abandon', 'menu_exit', 'quit', 'debug')
  and max_depth >= 0
  and rooms_cleared >= 0
  and jsonb_typeof(death_event) = 'object'
  and jsonb_typeof(damage_events) = 'array'
  and jsonb_typeof(reward_choices) = 'array'
  and jsonb_typeof(room_entries) = 'array'
  and jsonb_typeof(door_choices) = 'array'
  and jsonb_typeof(aggregate) = 'object'
  and upload_source = 'game_client'
);

-- Optional read policy for dashboard queries with anon key (disabled by default).
-- Uncomment only if you need client-side read access.
-- drop policy if exists telemetry_runs_select_anon on public.telemetry_runs;
-- create policy telemetry_runs_select_anon
-- on public.telemetry_runs
-- for select
-- to anon
-- using (false);
