-- Production telemetry schema for anonymous run uploads.
-- Run in Supabase SQL editor after the connectivity spike is validated.

create table if not exists public.telemetry_runs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  run_id text not null,
  started_at_unix bigint not null,
  ended_at_unix bigint not null,
  game_version text not null,
  character_id text not null default 'unknown',
  difficulty_tier int not null,
  run_mode int not null,
  outcome text not null,
  max_depth int not null,
  rooms_cleared int not null,
  is_debug boolean not null,
  death_event jsonb not null default '{}'::jsonb,
  damage_events jsonb not null default '[]'::jsonb,
  reward_choices jsonb not null default '[]'::jsonb,
  reward_offers jsonb not null default '[]'::jsonb,
  room_entries jsonb not null default '[]'::jsonb,
  door_choices jsonb not null default '[]'::jsonb,
  aggregate jsonb not null default '{}'::jsonb,
  upload_source text not null default 'game_client'
);

alter table public.telemetry_runs add column if not exists damage_events jsonb not null default '[]'::jsonb;
alter table public.telemetry_runs add column if not exists reward_choices jsonb not null default '[]'::jsonb;
alter table public.telemetry_runs add column if not exists character_id text not null default 'unknown';
alter table public.telemetry_runs add column if not exists reward_offers jsonb not null default '[]'::jsonb;
alter table public.telemetry_runs add column if not exists room_entries jsonb not null default '[]'::jsonb;
alter table public.telemetry_runs add column if not exists door_choices jsonb not null default '[]'::jsonb;

create unique index if not exists telemetry_runs_run_id_idx
  on public.telemetry_runs (run_id);

alter table public.telemetry_runs enable row level security;

-- Restrict anonymous writes to expected shape and bounded values.
drop policy if exists telemetry_runs_insert_anon on public.telemetry_runs;
create policy telemetry_runs_insert_anon
on public.telemetry_runs
for insert
to anon
with check (
  length(trim(run_id)) >= 8
  and started_at_unix > 0
  and ended_at_unix >= started_at_unix
  and length(trim(character_id)) > 0
  and difficulty_tier between 0 and 3
  and run_mode in (0, 1)
  and outcome in ('clear', 'death', 'abandon', 'menu_exit', 'quit', 'debug')
  and max_depth >= 0
  and rooms_cleared >= 0
  and jsonb_typeof(death_event) = 'object'
  and jsonb_typeof(damage_events) = 'array'
  and jsonb_typeof(reward_choices) = 'array'
  and jsonb_typeof(reward_offers) = 'array'
  and jsonb_typeof(room_entries) = 'array'
  and jsonb_typeof(door_choices) = 'array'
  and jsonb_typeof(aggregate) = 'object'
  and upload_source = 'game_client'
);

-- Optional read policy for dashboard queries with anon key (disabled by default).
-- Uncomment only if you need client-side read access.
-- drop policy if exists telemetry_runs_select_anon on public.telemetry_runs;
-- create policy telemetry_runs_select_anon
-- on public.telemetry_runs
-- for select
-- to anon
-- using (false);

-- Hardened read RPC for tooling: returns only the latest run payload.
-- This avoids broad anon SELECT access on the table while still allowing
-- client-side analysis helpers to fetch one run at a time.
drop function if exists public.get_latest_balance_run(boolean, text, integer);
create or replace function public.get_latest_balance_run(
  p_include_debug boolean default false,
  p_game_version text default '',
  p_max_age_days integer default 120
)
returns jsonb
language sql
security definer
set search_path = public
as $$
  with picked as (
    select
      run_id,
      started_at_unix,
      ended_at_unix,
      game_version,
      character_id,
      difficulty_tier,
      run_mode,
      outcome,
      max_depth,
      rooms_cleared,
      is_debug,
      death_event,
      damage_events,
      reward_choices,
      reward_offers,
      room_entries,
      door_choices,
      aggregate,
      upload_source
    from public.telemetry_runs
    where (p_include_debug or is_debug = false)
      and (
        nullif(trim(p_game_version), '') is null
        or game_version = nullif(trim(p_game_version), '')
      )
      and started_at_unix >= (
        extract(epoch from now())::bigint - greatest(p_max_age_days, 1) * 86400
      )
    order by started_at_unix desc
    limit 1
  )
  select coalesce((select to_jsonb(picked) from picked), '{}'::jsonb);
$$;

revoke all on function public.get_latest_balance_run(boolean, text, integer) from public;
grant execute on function public.get_latest_balance_run(boolean, text, integer) to anon;
grant execute on function public.get_latest_balance_run(boolean, text, integer) to authenticated;

-- Hardened read RPC for batch analysis: returns runs for one UTC day.
-- Default day is "today" in UTC.
drop function if exists public.get_balance_runs_for_day(date, boolean, text, integer);
create or replace function public.get_balance_runs_for_day(
  p_day_utc date default (now() at time zone 'utc')::date,
  p_include_debug boolean default false,
  p_game_version text default '',
  p_max_runs integer default 500
)
returns jsonb
language sql
security definer
set search_path = public
as $$
  with bounds as (
    select
      extract(epoch from (p_day_utc::timestamp at time zone 'utc'))::bigint as day_start_unix,
      extract(epoch from ((p_day_utc::timestamp + interval '1 day') at time zone 'utc'))::bigint as day_end_unix
  ),
  picked as (
    select
      run_id,
      started_at_unix,
      ended_at_unix,
      game_version,
      character_id,
      difficulty_tier,
      run_mode,
      outcome,
      max_depth,
      rooms_cleared,
      is_debug,
      death_event,
      damage_events,
      reward_choices,
      reward_offers,
      room_entries,
      door_choices,
      aggregate,
      upload_source
    from public.telemetry_runs, bounds
    where started_at_unix >= bounds.day_start_unix
      and started_at_unix < bounds.day_end_unix
      and (p_include_debug or is_debug = false)
      and (
        nullif(trim(p_game_version), '') is null
        or game_version = nullif(trim(p_game_version), '')
      )
    order by started_at_unix desc
    limit greatest(1, least(p_max_runs, 2000))
  )
  select coalesce((select jsonb_agg(to_jsonb(picked)) from picked), '[]'::jsonb);
$$;

revoke all on function public.get_balance_runs_for_day(date, boolean, text, integer) from public;
grant execute on function public.get_balance_runs_for_day(date, boolean, text, integer) to anon;
grant execute on function public.get_balance_runs_for_day(date, boolean, text, integer) to authenticated;

-- Hardened read RPC for open window analysis by unix timestamp.
drop function if exists public.get_balance_runs_between(bigint, bigint, boolean, text, integer);
create or replace function public.get_balance_runs_between(
  p_start_unix bigint,
  p_end_unix bigint,
  p_include_debug boolean default false,
  p_game_version text default '',
  p_max_runs integer default 1000
)
returns jsonb
language sql
security definer
set search_path = public
as $$
  with picked as (
    select
      run_id,
      started_at_unix,
      ended_at_unix,
      game_version,
      character_id,
      difficulty_tier,
      run_mode,
      outcome,
      max_depth,
      rooms_cleared,
      is_debug,
      death_event,
      damage_events,
      reward_choices,
      reward_offers,
      room_entries,
      door_choices,
      aggregate,
      upload_source
    from public.telemetry_runs
    where started_at_unix >= least(p_start_unix, p_end_unix)
      and started_at_unix < greatest(p_start_unix, p_end_unix)
      and (p_include_debug or is_debug = false)
      and (
        nullif(trim(p_game_version), '') is null
        or game_version = nullif(trim(p_game_version), '')
      )
    order by started_at_unix desc
    limit greatest(1, least(p_max_runs, 5000))
  )
  select coalesce((select jsonb_agg(to_jsonb(picked)) from picked), '[]'::jsonb);
$$;

revoke all on function public.get_balance_runs_between(bigint, bigint, boolean, text, integer) from public;
grant execute on function public.get_balance_runs_between(bigint, bigint, boolean, text, integer) to anon;
grant execute on function public.get_balance_runs_between(bigint, bigint, boolean, text, integer) to authenticated;

-- Online leaderboard storage for clear runs only.
create table if not exists public.leaderboard_runs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  run_id text not null,
  player_uuid text not null,
  player_name text not null,
  character_id text not null,
  character_name text not null,
  difficulty_tier int not null,
  outcome text not null,
  duration_seconds int not null,
  clear_time_ms bigint not null,
  leaderboard_patch_key text not null,
  started_at_unix bigint not null,
  ended_at_unix bigint not null,
  is_debug boolean not null default false,
  run_summary jsonb not null default '{}'::jsonb
);

alter table public.leaderboard_runs add column if not exists updated_at timestamptz not null default now();
alter table public.leaderboard_runs add column if not exists run_summary jsonb not null default '{}'::jsonb;
alter table public.leaderboard_runs add column if not exists clear_time_ms bigint not null default 0;

create unique index if not exists leaderboard_runs_run_id_idx
  on public.leaderboard_runs (run_id);

create index if not exists leaderboard_runs_board_lookup_idx
  on public.leaderboard_runs (leaderboard_patch_key, difficulty_tier, character_id, duration_seconds, ended_at_unix, run_id);

create index if not exists leaderboard_runs_player_lookup_idx
  on public.leaderboard_runs (player_uuid, leaderboard_patch_key, difficulty_tier, character_id, duration_seconds);

alter table public.leaderboard_runs enable row level security;

drop policy if exists leaderboard_runs_insert_anon on public.leaderboard_runs;
create policy leaderboard_runs_insert_anon
on public.leaderboard_runs
for insert
to anon
with check (
  length(trim(run_id)) >= 8
  and length(trim(player_uuid)) >= 8
  and length(trim(player_name)) >= 1
  and length(trim(character_id)) >= 1
  and difficulty_tier between 0 and 3
  and outcome = 'clear'
  and duration_seconds > 0
  and clear_time_ms > 0
  and length(trim(leaderboard_patch_key)) >= 1
  and started_at_unix > 0
  and ended_at_unix >= started_at_unix
  and is_debug = false
  and jsonb_typeof(run_summary) = 'object'
);

drop policy if exists leaderboard_runs_select_anon on public.leaderboard_runs;
create policy leaderboard_runs_select_anon
on public.leaderboard_runs
for select
to anon
using (false);

drop function if exists public.submit_leaderboard_run(jsonb);
create or replace function public.submit_leaderboard_run(
  p_run_summary jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_run_id text := lower(trim(coalesce(p_run_summary->>'run_id', '')));
  v_player_uuid text := lower(trim(coalesce(p_run_summary->>'player_uuid', '')));
  v_player_name text := trim(coalesce(p_run_summary->>'player_name', 'Player'));
  v_character_id text := lower(trim(coalesce(p_run_summary->>'character_id', 'unknown')));
  v_character_name text := trim(coalesce(p_run_summary->>'character_name', 'Unknown'));
  v_patch_key text := lower(trim(coalesce(p_run_summary->>'leaderboard_patch_key', 'dev')));
  v_outcome text := lower(trim(coalesce(p_run_summary->>'outcome', 'unknown')));
  v_duration_seconds int := greatest(0, coalesce((p_run_summary->>'duration_seconds')::int, 0));
  v_started_at_unix bigint := greatest(0, coalesce((p_run_summary->>'started_at_unix')::bigint, 0));
  v_ended_at_unix bigint := greatest(0, coalesce((p_run_summary->>'ended_at_unix')::bigint, 0));
  v_difficulty_tier int := coalesce((p_run_summary->>'difficulty_tier')::int, -1);
  v_is_debug boolean := coalesce((p_run_summary->>'is_debug')::boolean, false);
  v_clear_time_ms bigint;
begin
  if v_run_id = '' then
    return jsonb_build_object('ok', false, 'error', 'missing_run_id');
  end if;
  if v_player_uuid = '' then
    return jsonb_build_object('ok', false, 'error', 'missing_player_uuid');
  end if;
  if v_outcome <> 'clear' then
    return jsonb_build_object('ok', false, 'error', 'outcome_not_clear');
  end if;
  if v_is_debug then
    return jsonb_build_object('ok', false, 'error', 'debug_not_eligible');
  end if;
  if v_difficulty_tier < 0 or v_difficulty_tier > 3 then
    return jsonb_build_object('ok', false, 'error', 'invalid_difficulty_tier');
  end if;
  if v_duration_seconds <= 0 then
    return jsonb_build_object('ok', false, 'error', 'invalid_duration');
  end if;
  if v_started_at_unix <= 0 then
    return jsonb_build_object('ok', false, 'error', 'invalid_started_at');
  end if;
  if v_ended_at_unix < v_started_at_unix then
    return jsonb_build_object('ok', false, 'error', 'invalid_ended_at');
  end if;
  if v_player_name = '' then
    v_player_name := 'Player';
  end if;
  if v_patch_key = '' then
    v_patch_key := 'dev';
  end if;

  v_clear_time_ms := (v_duration_seconds::bigint * 1000);

  insert into public.leaderboard_runs (
    run_id,
    player_uuid,
    player_name,
    character_id,
    character_name,
    difficulty_tier,
    outcome,
    duration_seconds,
    clear_time_ms,
    leaderboard_patch_key,
    started_at_unix,
    ended_at_unix,
    is_debug,
    run_summary,
    updated_at
  ) values (
    v_run_id,
    v_player_uuid,
    v_player_name,
    v_character_id,
    v_character_name,
    v_difficulty_tier,
    'clear',
    v_duration_seconds,
    v_clear_time_ms,
    v_patch_key,
    v_started_at_unix,
    v_ended_at_unix,
    false,
    coalesce(p_run_summary, '{}'::jsonb),
    now()
  )
  on conflict (run_id) do update
  set
    player_uuid = excluded.player_uuid,
    player_name = excluded.player_name,
    character_id = excluded.character_id,
    character_name = excluded.character_name,
    difficulty_tier = excluded.difficulty_tier,
    duration_seconds = excluded.duration_seconds,
    clear_time_ms = excluded.clear_time_ms,
    leaderboard_patch_key = excluded.leaderboard_patch_key,
    started_at_unix = excluded.started_at_unix,
    ended_at_unix = excluded.ended_at_unix,
    is_debug = excluded.is_debug,
    run_summary = excluded.run_summary,
    updated_at = now();

  return jsonb_build_object('ok', true, 'run_id', v_run_id);
end;
$$;

revoke all on function public.submit_leaderboard_run(jsonb) from public;
grant execute on function public.submit_leaderboard_run(jsonb) to anon;
grant execute on function public.submit_leaderboard_run(jsonb) to authenticated;

drop function if exists public.get_leaderboard_top(text, integer, text, text, integer);
create or replace function public.get_leaderboard_top(
  p_patch_key text,
  p_difficulty_tier integer,
  p_board_mode text default 'global',
  p_character_id text default '',
  p_limit integer default 25
)
returns jsonb
language sql
security definer
set search_path = public
as $$
  with filtered as (
    select
      run_id,
      player_uuid,
      player_name,
      character_id,
      character_name,
      difficulty_tier,
      duration_seconds,
      leaderboard_patch_key,
      ended_at_unix
    from public.leaderboard_runs
    where is_debug = false
      and outcome = 'clear'
      and leaderboard_patch_key = lower(trim(p_patch_key))
      and difficulty_tier = p_difficulty_tier
      and (
        lower(trim(coalesce(p_board_mode, 'global'))) <> 'per_character'
        or character_id = lower(trim(coalesce(p_character_id, '')))
      )
  ),
  best_per_player as (
    select distinct on (player_uuid)
      run_id,
      player_uuid,
      player_name,
      character_id,
      character_name,
      difficulty_tier,
      duration_seconds,
      leaderboard_patch_key,
      ended_at_unix
    from filtered
    order by player_uuid, duration_seconds asc, ended_at_unix asc, run_id asc
  ),
  ranked as (
    select
      row_number() over(order by duration_seconds asc, ended_at_unix asc, run_id asc) as rank,
      run_id,
      player_uuid,
      player_name,
      character_id,
      character_name,
      difficulty_tier,
      duration_seconds,
      leaderboard_patch_key,
      ended_at_unix
    from best_per_player
    order by duration_seconds asc, ended_at_unix asc, run_id asc
    limit greatest(1, least(p_limit, 25))
  )
  select coalesce((select jsonb_agg(to_jsonb(ranked)) from ranked), '[]'::jsonb);
$$;

revoke all on function public.get_leaderboard_top(text, integer, text, text, integer) from public;
grant execute on function public.get_leaderboard_top(text, integer, text, text, integer) to anon;
grant execute on function public.get_leaderboard_top(text, integer, text, text, integer) to authenticated;

drop function if exists public.get_leaderboard_patch_keys(integer, integer, text);
create or replace function public.get_leaderboard_patch_keys(
  p_difficulty_tier integer default -1,
  p_limit integer default 24,
  p_current_patch_key text default ''
)
returns jsonb
language sql
security definer
set search_path = public
as $$
  with patches as (
    select distinct leaderboard_patch_key as patch_key
    from public.leaderboard_runs
    where is_debug = false
      and outcome = 'clear'
      and (
        p_difficulty_tier < 0
        or difficulty_tier = p_difficulty_tier
      )
  ),
  ordered as (
    select
      patch_key,
      patch_key = lower(trim(coalesce(p_current_patch_key, ''))) as is_current,
      patch_key <> lower(trim(coalesce(p_current_patch_key, ''))) as is_archived
    from patches
    order by patch_key desc
    limit greatest(1, least(p_limit, 40))
  )
  select coalesce((select jsonb_agg(to_jsonb(ordered)) from ordered), '[]'::jsonb);
$$;

revoke all on function public.get_leaderboard_patch_keys(integer, integer, text) from public;
grant execute on function public.get_leaderboard_patch_keys(integer, integer, text) to anon;
grant execute on function public.get_leaderboard_patch_keys(integer, integer, text) to authenticated;
