extends "res://scripts/tests/render_breakwater.gd"
## Native rendering of committed geometry at real room-fit zoom.

func _combat_frames() -> void:
	await _prepare()
	actor.global_position = Vector2(390.0, 80.0)
	var boss := _apex(Vector2(440.0, 80.0))
	await physics_frame
	boss._begin_harbor_gate()
	await _capture("harbor_brace", "BREAKWATER / HARBOR GATE", "The shore and calm opening commit for 1.2 seconds. Breakwater braces sideways into the neighboring crest.", boss)
	boss._process_behavior(0.55)
	await _capture("harbor_step", "BREAKWATER / COMMITTED BRACE STEP", "The opening stays where the player started. Following the lateral brace too early leaves that shelter.", boss)
	var packet := boss._get_custom_network_runtime_state()
	boss.hide()
	var replica := _apex(boss.global_position + Vector2(15.0, 10.0))
	replica.set_network_simulation_enabled(false)
	replica._apply_custom_network_runtime_state(packet)
	_check(replica.get_warning_polygons() == boss.get_warning_polygons(), "Native replica draws exactly the same committed gate despite body interpolation")
	await _capture("harbor_joiner", "BREAKWATER / JOINING PLAYER WARNING", "The host's fixed shoreline, opening rails and plain warm callout remain identical on the replica.", replica)
	replica.free()
	boss.show()
	boss._process_behavior(BREAKWATER.GATE_WARNING)
	boss._process_behavior(0.45)
	await _capture("harbor_crossing", "BREAKWATER / THE SEAWALL CROSSES", "Only the bright moving crest is dangerous. The calm opening and the floor behind the crest stay safe.", boss)
	boss._process_behavior(0.80)
	await _capture("harbor_crossing_late", "BREAKWATER / PURSUE AFTER THE CREST", "Once the seawall passes your position, the cleared floor gives room to approach the braced Apex.", boss)
	boss._process_behavior(10.0)
	await _capture("harbor_recovery", "BREAKWATER / SPENT SEAWALL", "The 1.1-second open recovery leads back to the ram, which asks for a sidestep rather than holding position.", boss)
	await _release_room()
	await _prepare()
	actor.global_position = Vector2(480.0, -300.0)
	boss = _apex(Vector2(0.0, -30.0))
	var peers: Array[Probe] = []
	for index in range(3):
		var probe := Probe.new()
		probe.player_id = index + 2
		room.add_child(probe)
		probe.global_position = Vector2(460.0, -100.0 + index * 200.0)
		peers.append(probe)
	boss._begin_harbor_gate()
	await _capture("harbor_four_openings", "BREAKWATER / FOUR COMMITTED OPENINGS", "Each participant starts in a bounded calm lane. The entire shoreline is covered between those openings.", boss)
	for peer in peers:
		peer.global_position = actor.global_position + Vector2(0.0, 18.0)
	boss._begin_harbor_gate()
	await _capture("harbor_merged_openings", "BREAKWATER / OVERLAPPING OPENINGS", "Nearby participants share one clean opening. The rest of the shore remains a readable crossing.", boss)
	await _release_room()
	await _prepare()
	actor.global_position = Vector2(-550.0, -400.0)
	boss = _apex(Vector2(-400.0, -250.0))
	_thin_cover(actor.global_position + Vector2(75.0, 60.0))
	boss._begin_harbor_gate()
	await _capture("harbor_corner", "BREAKWATER / CORNER OPENING", "A committed opening reaches the actual arena edge. Slowed players can hold it beside inner cover.", boss)
	await _release_room()
	await _prepare()
	actor.global_position = Vector2(-140.0, 370.0)
	boss = _apex(Vector2(-90.0, 190.0))
	boss._begin_harbor_gate()
	await _capture("harbor_other_shore", "BREAKWATER / ANOTHER SHORE", "The nearest shore to the chosen player sets the crossing direction; the warning never turns afterward.", boss)
	await _release_room()
